a,b = int(input("Enter a value: ")),int(input("Enter b value: "))
print("Sum = ",a + b)
print("sub = ",a - b)
print("mul = ",a * b)
print("div = ",a / b)
print("mod = ",a % b)
print("exp = ",a ** b)
print("floordiv = ",a // b)
